In [1]:
import pandas as pd

In [8]:
pd.set_option('display.max_colwidth', None)

df = pd.read_csv("./2W_2L/tuning_runs.csv")
df = df[df["loss_fn"]=="symile-all-negs"]

len(df)

108

In [13]:
idx = df.groupby(['loss_fn'])['val_loss'].idxmin()
df.loc[idx]

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path
232,20240505_053048_7256,symile-all-negs,/gpfs/scratch/as16583/ckpts/high_dim/20240505_053048_7256/epoch=9-val_loss=5.6003-val_accuracy=0.9224.ckpt,9,5.6003,0.9224,0.0,0.00005,https://wandb.ai/rajesh-lab/symile/runs/zz15mf7h

In [14]:
df[df['loss_fn']=="symile-all-negs"].sort_values(by="val_loss", ascending=True).head(1)

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path
232,20240505_053048_7256,symile-all-negs,/gpfs/scratch/as16583/ckpts/high_dim/20240505_053048_7256/epoch=9-val_loss=5.6003-val_accuracy=0.9224.ckpt,9,5.6003,0.9224,0.0,0.00005,https://wandb.ai/rajesh-lab/symile/runs/zz15mf7h

In [15]:
idx = df.groupby(['loss_fn'])['val_accuracy'].idxmax()
df.loc[idx]

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path
241,20240505_061947_1913,symile-all-negs,/gpfs/scratch/as16583/ckpts/high_dim/20240505_061947_1913/epoch=3-val_loss=5.6790-val_accuracy=0.9428.ckpt,3,5.679,0.9428,0.0,0.00001,https://wandb.ai/rajesh-lab/symile/runs/yi241fbx

In [16]:
df[df['loss_fn']=="symile-all-negs"].sort_values(by="val_accuracy", ascending=False).head(1)

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path
313,20240507_050818_5995,symile-all-negs,/gpfs/scratch/as16583/ckpts/high_dim/20240507_050818_5995/epoch=3-val_loss=5.6790-val_accuracy=0.9428.ckpt,3,5.679,0.9428,0.001,0.00001,https://wandb.ai/rajesh-lab/symile/runs/na8czibf