In [26]:
import pandas as pd

In [101]:
pd.set_option('display.max_colwidth', None)

# df_2 = pd.read_csv("./2W_2L/tuning_runs.csv")
# df_2["num_words"] = 2

# df_5 = pd.read_csv("./5W_5L/tuning_runs.csv")
# df_5["num_words"] = 5

df_10 = pd.read_csv("./10W_10L/tuning_runs.csv")
# df_10["num_words"] = 10

In [102]:
df = df_10
loss_fn = "symile"

In [103]:
# get rid of the second repeat epoch

# Step 1: Convert run_name to datetime
df['datetime'] = pd.to_datetime(df['run_name'].str[:15], format='%Y%m%d_%H%M%S')

# Step 2: Sort the DataFrame by the datetime column
df = df.sort_values(by='datetime')

# Step 3: Drop duplicates based on the specified columns, keep the first (earliest due to sort)
df = df.drop_duplicates(subset=['loss_fn', 'epoch', 'weight_decay', 'learning_rate', 'wandb_path'], keep='first')

In [104]:
len(df[(df.epoch == 17)])

18

In [105]:
idx = df.groupby(['loss_fn'])['val_loss'].idxmin()
df.loc[idx]

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path,datetime
173,20240428_163214_9359,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240428_163214_9359/epoch=5-val_loss=13.9158-val_accuracy=0.0927.ckpt,5,13.915809,0.092746,0.001,0.0001,https://wandb.ai/rajesh-lab/symile/runs/sufiw40q,2024-04-28 16:32:14
84,20240503_040432_1179,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240503_040432_1179/epoch=23-val_loss=0.7692-val_accuracy=0.8820.ckpt,23,0.769159,0.882036,0.000,0.0001,https://wandb.ai/rajesh-lab/symile/runs/y3adquhx,2024-05-03 04:04:32

In [106]:
df[df['loss_fn']==loss_fn].sort_values(by="val_loss", ascending=True).head(1)

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path,datetime
84,20240503_040432_1179,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240503_040432_1179/epoch=23-val_loss=0.7692-val_accuracy=0.8820.ckpt,23,0.769159,0.882036,0.0,0.0001,https://wandb.ai/rajesh-lab/symile/runs/y3adquhx,2024-05-03 04:04:32

In [107]:
idx = df.groupby(['loss_fn'])['val_accuracy'].idxmax()
df.loc[idx]

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path,datetime
143,20240427_194543_6394,clip,/gpfs/scratch/as16583/ckpts/high_dim/20240427_194543_6394/epoch=17-val_loss=14.0296-val_accuracy=0.0935.ckpt,17,14.029621,0.093524,0.0,0.00001,https://wandb.ai/rajesh-lab/symile/runs/1ns9112p,2024-04-27 19:45:43
87,20240503_040432_4963,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240503_040432_4963/epoch=21-val_loss=0.8026-val_accuracy=0.8858.ckpt,21,0.802632,0.885754,0.0,0.00005,https://wandb.ai/rajesh-lab/symile/runs/nwotrt47,2024-05-03 04:04:32

In [108]:
df[df['loss_fn']==loss_fn].sort_values(by="val_accuracy", ascending=False).head(1)

,run_name,loss_fn,ckpt_pt,epoch,val_loss,val_accuracy,weight_decay,learning_rate,wandb_path,datetime
99,20240503_074331_1493,symile,/gpfs/scratch/as16583/ckpts/high_dim/20240503_074331_1493/epoch=21-val_loss=0.8026-val_accuracy=0.8858.ckpt,21,0.802632,0.885754,0.0001,0.00005,https://wandb.ai/rajesh-lab/symile/runs/hgx3k2ll,2024-05-03 07:43:31