In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_colwidth', None)

df = pd.read_csv("diff_seeds.csv")
# df = df[df['weight_decay'].isin([0.1, 0.5, 1.0])]

len(df)

12000

In [3]:
col_to_keep = ['loss_fn', 'seed',
       'weight_decay', 'learning_rate',
       'epoch',
       'run_name', 'ckpt_pt', 'wandb_path',
       'val_loss',
       'val_true_cxr_acc_at_1', 'val_true_cxr_acc_at_5', 'val_true_cxr_acc_at_10',
       'val_label_acc_at_1', 'val_label_acc_at_5', 'val_label_acc_at_10',
       'val_label_precision_at_1', 'val_label_precision_at_5', 'val_label_precision_at_10'
       ]
df = df[col_to_keep]

In [76]:
idx = df.groupby(['loss_fn', 'seed'])['val_true_cxr_acc_at_1'].idxmax()
df.loc[idx]

,loss_fn,seed,weight_decay,learning_rate,epoch,run_name,ckpt_pt,wandb_path,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10,val_label_precision_at_1,val_label_precision_at_5,val_label_precision_at_10
6824,clip,0,0.100,0.0100,24,20240428_054506_3065,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240428_054506_3065/epoch=24-val_loss=15.4240.ckpt,https://wandb.ai/rajesh-lab/symile/runs/44w9vmsz,15.424027,0.20,0.28,0.28,0.20,0.36,0.64,0.20,0.088,0.088
8716,clip,1,0.010,0.0005,16,20240516_160134_0324,/gpfs/data/ranganathlab/cxr_prediction_ckpts/20240516_160134_0324/epoch=16-val_loss=15.7311.ckpt,https://wandb.ai/rajesh-lab/symile/runs/5h6yihcs,15.731075,0.24,0.44,0.48,0.28,0.64,0.72,0.28,0.152,0.108
10329,clip,2,0.001,0.0005,29,20240516_214059_2834,/gpfs/data/ranganathlab/cxr_prediction_ckpts/20240516_214059_2834/epoch=29-val_loss=20.1912.ckpt,https://wandb.ai/rajesh-lab/symile/runs/yhkj53yi,20.191225,0.20,0.36,0.52,0.24,0.40,0.64,0.24,0.112,0.096
868,symile,0,0.100,0.0100,68,20240506_213158_4943,/gpfs/data/ranganathlab/cxr_prediction_ckpts/20240506_213158_4943/epoch=68-val_loss=20.5503.ckpt,https://wandb.ai/rajesh-lab/symile/runs/bir4csof,20.550314,0.32,0.44,0.52,0.36,0.56,0.80,0.36,0.144,0.120
3745,symile,1,1.000,0.0050,45,20240516_235351_8765,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240516_235351_8765/epoch=45-val_loss=10.4198.ckpt,https://wandb.ai/rajesh-lab/symile/runs/vd9zxu9l,10.419784,0.28,0.36,0.36,0.32,0.72,0.84,0.32,0.168,0.108
4477,symile,2,0.010,0.0100,77,20240517_024101_8198,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240517_024101_8198/epoch=77-val_loss=42.1374.ckpt,https://wandb.ai/rajesh-lab/symile/runs/f4e1ihdn,42.137356,0.24,0.24,0.36,0.24,0.32,0.48,0.24,0.064,0.072

In [4]:
idx = df.groupby(['loss_fn', 'seed'])['val_true_cxr_acc_at_1'].idxmax()
df.loc[idx]

,loss_fn,seed,weight_decay,learning_rate,epoch,run_name,ckpt_pt,wandb_path,val_loss,val_true_cxr_acc_at_1,val_true_cxr_acc_at_5,val_true_cxr_acc_at_10,val_label_acc_at_1,val_label_acc_at_5,val_label_acc_at_10,val_label_precision_at_1,val_label_precision_at_5,val_label_precision_at_10
6824,clip,0,0.100,0.0100,24,20240428_054506_3065,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240428_054506_3065/epoch=24-val_loss=15.4240.ckpt,https://wandb.ai/rajesh-lab/symile/runs/44w9vmsz,15.424027,0.20,0.28,0.28,0.20,0.36,0.64,0.20,0.088,0.088
8716,clip,1,0.010,0.0005,16,20240516_160134_0324,/gpfs/data/ranganathlab/cxr_prediction_ckpts/20240516_160134_0324/epoch=16-val_loss=15.7311.ckpt,https://wandb.ai/rajesh-lab/symile/runs/5h6yihcs,15.731075,0.24,0.44,0.48,0.28,0.64,0.72,0.28,0.152,0.108
10329,clip,2,0.001,0.0005,29,20240516_214059_2834,/gpfs/data/ranganathlab/cxr_prediction_ckpts/20240516_214059_2834/epoch=29-val_loss=20.1912.ckpt,https://wandb.ai/rajesh-lab/symile/runs/yhkj53yi,20.191225,0.20,0.36,0.52,0.24,0.40,0.64,0.24,0.112,0.096
868,symile,0,0.100,0.0100,68,20240506_213158_4943,/gpfs/data/ranganathlab/cxr_prediction_ckpts/20240506_213158_4943/epoch=68-val_loss=20.5503.ckpt,https://wandb.ai/rajesh-lab/symile/runs/bir4csof,20.550314,0.32,0.44,0.52,0.36,0.56,0.80,0.36,0.144,0.120
3745,symile,1,1.000,0.0050,45,20240516_235351_8765,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240516_235351_8765/epoch=45-val_loss=10.4198.ckpt,https://wandb.ai/rajesh-lab/symile/runs/vd9zxu9l,10.419784,0.28,0.36,0.36,0.32,0.72,0.84,0.32,0.168,0.108
4477,symile,2,0.010,0.0100,77,20240517_024101_8198,/gpfs/scratch/as16583/ckpts/cxr_prediction/20240517_024101_8198/epoch=77-val_loss=42.1374.ckpt,https://wandb.ai/rajesh-lab/symile/runs/f4e1ihdn,42.137356,0.24,0.24,0.36,0.24,0.32,0.48,0.24,0.064,0.072

In [ ]:
idx = df.groupby(['loss_fn', 'seed', 'learning_rate', 'weight_decay'])['val_loss'].idxmin()
df.loc[idx]

In [2]:
pd.set_option('display.max_colwidth', None)

df = pd.read_csv("diff_seeds.csv")
df_june = pd.read_csv("diff_seeds_june.csv")

In [3]:
len(df)

12000

In [4]:
len(df_june)

11600