In [1]:
import pandas as pd

In [25]:
pd.set_option('display.max_colwidth', None)

df = pd.read_csv("tuning_runs.csv")

df = df[df['pretrained'] == False]
df = df[~df['weight_decay'].isin([1.0, 0.5])]

len(df)

4800

In [26]:
idx = df.groupby(['loss_fn'])['val_loss'].idxmin()
df.loc[idx]

,run_name,loss_fn,ckpt_pt,pretrained,risk_model,weight_decay,learning_rate,wandb_path,epoch,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10
8611,20240501_163354_6723,clip,/gpfs/data/ranganathlab/risk_prediction_ckpts/20240501_163354_6723/epoch=11-val_loss=14.6079.ckpt,False,mlp,0.01,0.001,https://wandb.ai/rajesh-lab/symile/runs/cd3qybn9,11,14.607912,0.272017,0.685623,0.907772
4621,20240504_113841_0583,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20240504_113841_0583/epoch=21-val_loss=3.7489.ckpt,False,ftt,0.01,0.001,https://wandb.ai/rajesh-lab/symile/runs/rs6lgrjx,21,3.748915,0.290381,0.707995,0.909091

In [27]:
df[df['loss_fn']=="symile"].sort_values(by="val_loss", ascending=True).head(1)

,run_name,loss_fn,ckpt_pt,pretrained,risk_model,weight_decay,learning_rate,wandb_path,epoch,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10
4621,20240504_113841_0583,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20240504_113841_0583/epoch=21-val_loss=3.7489.ckpt,False,ftt,0.01,0.001,https://wandb.ai/rajesh-lab/symile/runs/rs6lgrjx,21,3.748915,0.290381,0.707995,0.909091

In [28]:
idx = df.groupby(['loss_fn'])['val_acc_at_1'].idxmax()
df.loc[idx]

,run_name,loss_fn,ckpt_pt,pretrained,risk_model,weight_decay,learning_rate,wandb_path,epoch,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10
12788,20240504_001739_0983,clip,/gpfs/data/ranganathlab/risk_prediction_ckpts/20240504_001739_0983/epoch=88-val_loss=23.1743.ckpt,False,ftt,0.01,0.0005,https://wandb.ai/rajesh-lab/symile/runs/uxmp6tox,88,23.174345,0.356991,0.836090,0.970221
858,20240501_193035_6767,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20240501_193035_6767/epoch=58-val_loss=4.7050.ckpt,False,mlp,0.10,0.0100,https://wandb.ai/rajesh-lab/symile/runs/3itcimtu,58,4.704965,0.341518,0.765726,0.952516

In [29]:
df[df['loss_fn']=="symile"].sort_values(by="val_acc_at_1", ascending=False).head(1)

,run_name,loss_fn,ckpt_pt,pretrained,risk_model,weight_decay,learning_rate,wandb_path,epoch,val_loss,val_acc_at_1,val_acc_at_5,val_acc_at_10
858,20240501_193035_6767,symile,/gpfs/scratch/as16583/ckpts/risk_prediction/20240501_193035_6767/epoch=58-val_loss=4.7050.ckpt,False,mlp,0.1,0.01,https://wandb.ai/rajesh-lab/symile/runs/3itcimtu,58,4.704965,0.341518,0.765726,0.952516